nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  "@expo/cli@^0.7.3":
    peerDependencies:
      "expo-modules-autolinking": "^1.2.0"
  "babel-preset-expo@^9.3.2":
    peerDependencies:
      "@babel/core": "^7.20.0"
  "expo-asset@^8.9.2":
    peerDependencies:
      "expo": "^48.0.17"
  "expo-linking@^4.0.1":
    peerDependencies:
      "expo": "^48.0.17"
  "react-native@^0.71.8":
    peerDependencies:
      "@babel/preset-env": "^7.22.9"
  "react-native-codegen@^0.71.5":
    peerDependencies:
      "@babel/preset-env": "^7.22.9"
  "expo@^48.0.20":
    peerDependencies:
      "@babel/core": "^7.20.0"