version: '3.8'

services:

  frontend:
    image: m-cafe-frontend
    build:
      context: ./
      dockerfile: ./services/frontend/Dockerfile
    container_name: m-cafe-frontend
    env_file:
      - .docker-front.env
    depends_on:
      - nginx

  backend:
    image: m-cafe-backend
    build:
      context: ./
      dockerfile: ./services/backend/Dockerfile
    container_name: m-cafe-backend
    env_file:
      - .docker-back.env
    depends_on:
      - postgres_db
      - nginx

  nginx:
    image: nginx:1.25.1
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: m-cafe-reverse-proxy

volumes:
  pgdata:
