version: '3.8'

services:

  frontend:
    image: m-cafe-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - ./shared:/usr/src/shared
    container_name: m-cafe-frontend-dev
    env_file:
      - .dev.docker-front.env
    depends_on:
      - nginx

  postgres_db:
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    environment:
      POSTGRES_USER: vasuser
      POSTGRES_PASSWORD: crapassword
      POSTGRES_DB: cafe
    container_name: m-cafe-postgres_db-dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres_db
    container_name: m-cafe-adminer-dev
    depends_on:
      - postgres_db

  backend:
    image: m-cafe-backend-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
      - ./shared:/usr/src/shared
    container_name: m-cafe-backend-dev
    env_file:
      - .dev.docker-back.env
    depends_on:
      - postgres_db
      - nginx

  nginx:
    image: nginx:1.25.1
    restart: unless-stopped
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: m-cafe-reverse-proxy-dev

volumes:
  pgdata: