version: '3.8'

services:

  web-customer:
    image: m-cafe-web-dev-customer
    build:
      context: ./
      dockerfile: ./services/web/dev.Dockerfile
      target: run-stage-web-customer
    volumes:
      # Isolated frontend part to prevent reload on another target begin
      - ./services/web/customer:/usr/src/app/services/web/customer
      - ./services/web/shared:/usr/src/app/services/web/shared
      - ./services/web/webpack_config:/usr/src/app/services/web/webpack_config
      - ./services/web/package.json:/usr/src/app/services/web/package.json
      - ./services/web/tsconfig.json:/usr/src/app/services/web/tsconfig.json
      # Isolated frontend part to prevent reload on another target end
      # Isolated frontend-logic part to prevent reload on another target begin
      - ./packages/frontend-logic/src/customer:/usr/src/app/packages/frontend-logic/src/customer
      - ./packages/frontend-logic/src/shared:/usr/src/app/packages/frontend-logic/src/shared
      - ./packages/frontend-logic/src/types:/usr/src/app/packages/frontend-logic/src/types
      - ./packages/frontend-logic/src/utils:/usr/src/app/packages/frontend-logic/src/utils
      - ./packages/frontend-logic/package.json:/usr/src/app/packages/frontend-logic/package.json
      - ./packages/frontend-logic/tsconfig.json:/usr/src/app/packages/frontend-logic/tsconfig.json
      # Isolated frontend-logic part to prevent reload on another target end
      - ./packages/utils:/usr/src/app/packages/utils
      - ./packages/db:/usr/src/app/packages/db
      - ./packages/shared-backend-deps:/usr/src/app/packages/shared-backend-deps
      - ./packages/shared-frontend-deps:/usr/src/app/packages/shared-frontend-deps
      - ./packages/shared-constants:/usr/src/app/packages/shared-constants
      - ./packages/shared-dev-deps:/usr/src/app/packages/shared-dev-deps
    container_name: m-cafe-web-dev-customer
    env_file:
      - ./docker-envs/.dev.docker-front.env
      - ./docker-envs/.docker.validation-overrides.env

  web-admin:
    image: m-cafe-web-dev-admin
    build:
      context: ./
      dockerfile: ./services/web/dev.Dockerfile
      target: run-stage-web-admin
    volumes:
      # Isolated frontend part to prevent reload on another target begin
      - ./services/web/admin:/usr/src/app/services/web/admin
      - ./services/web/shared:/usr/src/app/services/web/shared
      - ./services/web/webpack_config:/usr/src/app/services/web/webpack_config
      - ./services/web/package.json:/usr/src/app/services/web/package.json
      - ./services/web/tsconfig.json:/usr/src/app/services/web/tsconfig.json
      # Isolated frontend part to prevent reload on another target end
      # Isolated frontend-logic part to prevent reload on another target begin
      - ./packages/frontend-logic/src/admin:/usr/src/app/packages/frontend-logic/src/admin
      - ./packages/frontend-logic/src/shared:/usr/src/app/packages/frontend-logic/src/shared
      - ./packages/frontend-logic/src/types:/usr/src/app/packages/frontend-logic/src/types
      - ./packages/frontend-logic/src/utils:/usr/src/app/packages/frontend-logic/src/utils
      - ./packages/frontend-logic/package.json:/usr/src/app/packages/frontend-logic/package.json
      - ./packages/frontend-logic/tsconfig.json:/usr/src/app/packages/frontend-logic/tsconfig.json
      # Isolated frontend-logic part to prevent reload on another target end
      - ./packages/utils:/usr/src/app/packages/utils
      - ./packages/db:/usr/src/app/packages/db
      - ./packages/shared-backend-deps:/usr/src/app/packages/shared-backend-deps
      - ./packages/shared-frontend-deps:/usr/src/app/packages/shared-frontend-deps
      - ./packages/shared-constants:/usr/src/app/packages/shared-constants
      - ./packages/shared-dev-deps:/usr/src/app/packages/shared-dev-deps
    container_name: m-cafe-web-dev-admin
    env_file:
      - ./docker-envs/.dev.docker-front.env
      - ./docker-envs/.docker.validation-overrides.env

  web-manager:
    image: m-cafe-web-dev-manager
    build:
      context: ./
      dockerfile: ./services/web/dev.Dockerfile
      target: run-stage-web-manager
    volumes:
      # Isolated frontend part to prevent reload on another target begin
      - ./services/web/manager:/usr/src/app/services/web/manager
      - ./services/web/shared:/usr/src/app/services/web/shared
      - ./services/web/webpack_config:/usr/src/app/services/web/webpack_config
      - ./services/web/package.json:/usr/src/app/services/web/package.json
      - ./services/web/tsconfig.json:/usr/src/app/services/web/tsconfig.json
      # Isolated frontend part to prevent reload on another target end
      # Isolated frontend-logic part to prevent reload on another target begin
      - ./packages/frontend-logic/src/manager:/usr/src/app/packages/frontend-logic/src/manager
      - ./packages/frontend-logic/src/shared:/usr/src/app/packages/frontend-logic/src/shared
      - ./packages/frontend-logic/src/types:/usr/src/app/packages/frontend-logic/src/types
      - ./packages/frontend-logic/src/utils:/usr/src/app/packages/frontend-logic/src/utils
      - ./packages/frontend-logic/package.json:/usr/src/app/packages/frontend-logic/package.json
      - ./packages/frontend-logic/tsconfig.json:/usr/src/app/packages/frontend-logic/tsconfig.json
      # Isolated frontend-logic part to prevent reload on another target end
      - ./packages/utils:/usr/src/app/packages/utils
      - ./packages/db:/usr/src/app/packages/db
      - ./packages/shared-backend-deps:/usr/src/app/packages/shared-backend-deps
      - ./packages/shared-frontend-deps:/usr/src/app/packages/shared-frontend-deps
      - ./packages/shared-constants:/usr/src/app/packages/shared-constants
      - ./packages/shared-dev-deps:/usr/src/app/packages/shared-dev-deps
    container_name: m-cafe-web-dev-manager
    env_file:
      - ./docker-envs/.dev.docker-front.env
      - ./docker-envs/.docker.validation-overrides.env

  redis:
    image: redis:7.0.12-alpine3.18
    container_name: m-cafe-redis-dev
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.dev.conf:/etc/redis/redis.conf:ro

  postgres_db:
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    environment:
      POSTGRES_USER: vasuser
      POSTGRES_PASSWORD: crapassword
      POSTGRES_DB: cafe
    container_name: m-cafe-postgres_db-dev
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: postgres_db
    container_name: m-cafe-adminer-dev
    depends_on:
      - postgres_db

  backend:
    image: m-cafe-backend-dev
    build:
      context: ./
      dockerfile: ./services/backend/dev.Dockerfile
    volumes:
      - ./services/backend:/usr/src/app/services/backend
      - ./packages/utils:/usr/src/app/packages/utils
      - ./packages/db:/usr/src/app/packages/db
      - ./packages/shared-backend-deps:/usr/src/app/packages/shared-backend-deps
      - ./packages/shared-constants:/usr/src/app/packages/shared-constants
      - ./packages/shared-dev-deps:/usr/src/app/packages/shared-dev-deps
    container_name: m-cafe-backend-dev
    env_file:
      - ./docker-envs/.dev.docker-back.env
      - ./docker-envs/.docker.validation-overrides.env
    depends_on:
      - postgres_db
      - redis

  nginx:
    image: nginx:1.25.1
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: m-cafe-reverse-proxy-dev

volumes:
  pgdata: