# NOT IMPLEMENTED

FROM redis:7.0.12-alpine3.18

# FROM redis:7.2-rc3-alpine3.18

# RUN apk add --no-cache \
#     stunnel \
#     python3 \
#     py3-pip

# RUN python3 -m pip install honcho==1.0.*

# WORKDIR /
# COPY stunnel.conf Procfile start.sh /
# RUN chmod +x start.sh

# ENV PYTHONUNBUFFERED=1